const ACOES_B3_DATA = [
    { ticker: "COGN3", nome: "Cogna", tipo: "EQUITY" },
    { ticker: "ENEV3", nome: "Eneva", tipo: "EQUITY" },
    { ticker: "AZUL4", nome: "Azul", tipo: "EQUITY" },
    { ticker: "B3SA3", nome: "B3", tipo: "EQUITY" },
    { ticker: "HAPV3", nome: "Hapvida", tipo: "EQUITY" },
    { ticker: "BBDC4", nome: "Banco Bradesco", tipo: "EQUITY" },
    { ticker: "BBAS3", nome: "Banco do Brasil", tipo: "EQUITY" },
    { ticker: "ITSA4", nome: "Itaúsa", tipo: "EQUITY" },
    { ticker: "RADL3", nome: "RaiaDrogasil", tipo: "EQUITY" },
    { ticker: "PETR4", nome: "Petrobras", tipo: "EQUITY" },
    { ticker: "RAIZ4", nome: "Raízen", tipo: "EQUITY" },
    { ticker: "ABEV3", nome: "Ambev", tipo: "EQUITY" },
    { ticker: "GOLL4", nome: "GOL", tipo: "EQUITY" },
    { ticker: "ITUB4", nome: "Itaú Unibanco", tipo: "EQUITY" },
    { ticker: "CPLE6", nome: "Copel", tipo: "EQUITY" },
    { ticker: "VALE3", nome: "Vale", tipo: "EQUITY" },
    { ticker: "MGLU3", nome: "Magazine Luiza", tipo: "EQUITY" },
    { ticker: "UGPA3", nome: "Ultrapar", tipo: "EQUITY" },
    { ticker: "CMIG4", nome: "Cemig", tipo: "EQUITY" },
    { ticker: "PRIO3", nome: "PetroRio", tipo: "EQUITY" },
    { ticker: "CSNA3", nome: "Siderúrgica Nacional", tipo: "EQUITY" },
    { ticker: "CSAN3", nome: "Cosan", tipo: "EQUITY" },
    { ticker: "BBDC3", nome: "Banco Bradesco", tipo: "EQUITY" },
    { ticker: "RAIL3", nome: "Rumo", tipo: "EQUITY" },
    { ticker: "GGBR4", nome: "Gerdau", tipo: "EQUITY" },
    { ticker: "NTCO3", nome: "Natura", tipo: "EQUITY" },
    { ticker: "VIVT3", nome: "Vivo", tipo: "EQUITY" },
    { ticker: "PETR3", nome: "Petrobras", tipo: "EQUITY" },
    { ticker: "GOAU4", nome: "Metalúrgica Gerdau", tipo: "EQUITY" },
    { ticker: "VBBR3", nome: "Vibra Energia", tipo: "EQUITY" },
    { ticker: "CRFB3", nome: "Carrefour Brasil", tipo: "EQUITY" },
    { ticker: "JBSS3", nome: "JBS", tipo: "EQUITY" },
    { ticker: "VAMO3", nome: "Grupo Vamos", tipo: "EQUITY" },
    { ticker: "WEGE3", nome: "WEG", tipo: "EQUITY" },
    { ticker: "TOTS3", nome: "Totvs", tipo: "EQUITY" },
    { ticker: "BEEF3", nome: "Minerva", tipo: "EQUITY" },
    { ticker: "RENT3", nome: "Localiza", tipo: "EQUITY" },
    { ticker: "MOTV3", nome: "Motiva", tipo: "EQUITY" },
    { ticker: "BPAC11", nome: "Banco BTG Pactual", tipo: "EQUITY" },
    { ticker: "CBAV3", nome: "CBA", tipo: "EQUITY" },
    { ticker: "SRNA3", nome: "Serena Energia", tipo: "EQUITY" },
    { ticker: "LREN3", nome: "Lojas Renner", tipo: "EQUITY" },
    { ticker: "PETZ3", nome: "Petz", tipo: "EQUITY" },
    { ticker: "POMO4", nome: "Marcopolo", tipo: "EQUITY" },
    { ticker: "ASAI3", nome: "Assaí", tipo: "EQUITY" },
    { ticker: "SUZB3", nome: "Suzano", tipo: "EQUITY" },
    { ticker: "EQTL3", nome: "Equatorial Energia", tipo: "EQUITY" },
    { ticker: "USIM5", nome: "Usiminas", tipo: "EQUITY" },
    { ticker: "CVCB3", nome: "CVC", tipo: "EQUITY" },
    { ticker: "TIMS3", nome: "TIM", tipo: "EQUITY" },
    { ticker: "CMIN3", nome: "CSN Mineração", tipo: "EQUITY" },
    { ticker: "ELET3", nome: "Eletrobras", tipo: "EQUITY" },
    { ticker: "ANIM3", nome: "Ânima Educação", tipo: "EQUITY" },
    { ticker: "IFCM3", nome: "Infracommerce", tipo: "EQUITY" },
    { ticker: "CASH3", nome: "Méliuz", tipo: "EQUITY" },
    { ticker: "MRVE3", nome: "MRV", tipo: "EQUITY" },
    { ticker: "AURE3", nome: "Auren Energia", tipo: "EQUITY" },
    { ticker: "KLBN11", nome: "Klabin", tipo: "EQUITY" },
    { ticker: "CXSE3", nome: "Caixa Seguridade", tipo: "EQUITY" },
    { ticker: "BBSE3", nome: "BB Seguridade", tipo: "EQUITY" },
    { ticker: "ECOR3", nome: "EcoRodovias", tipo: "EQUITY" },
    { ticker: "BRAV3", nome: "3R Petroleum", tipo: "EQUITY" },
    { ticker: "RAPT4", nome: "Randon", tipo: "EQUITY" },
    { ticker: "LWSA3", nome: "Locaweb", tipo: "EQUITY" },
    { ticker: "SBSP3", nome: "Sabesp", tipo: "EQUITY" },
    { ticker: "MRFG3", nome: "Marfrig", tipo: "EQUITY" },
    { ticker: "PCAR3", nome: "Grupo Pão de Açúcar", tipo: "EQUITY" },
    { ticker: "ENGI11", nome: "Energisa", tipo: "EQUITY" },
    { ticker: "FLRY3", nome: "Fleury", tipo: "EQUITY" },
    { ticker: "RDOR3", nome: "Rede D'Or", tipo: "EQUITY" },
    { ticker: "BRFS3", nome: "BRF", tipo: "EQUITY" },
    { ticker: "EGIE3", nome: "Engie", tipo: "EQUITY" },
    { ticker: "SMFT3", nome: "Smart Fit", tipo: "EQUITY" },
    { ticker: "EMBR3", nome: "Embraer", tipo: "EQUITY" },
    { ticker: "SIMH3", nome: "Simpar", tipo: "EQUITY" },
    { ticker: "STBP3", nome: "Santos Brasil", tipo: "EQUITY" },
    { ticker: "CYRE3", nome: "Cyrela", tipo: "EQUITY" },
    { ticker: "INTB3", nome: "Intelbras", tipo: "EQUITY" },
    { ticker: "CPFE3", nome: "CPFL Energia", tipo: "EQUITY" },
    { ticker: "CURY3", nome: "Cury", tipo: "EQUITY" },
    { ticker: "HYPE3", nome: "Hypera", tipo: "EQUITY" },
    { ticker: "MOVI3", nome: "Movida", tipo: "EQUITY" },
    { ticker: "CPLE3", nome: "Copel", tipo: "EQUITY" },
    { ticker: "IGTI11", nome: "Iguatemi", tipo: "EQUITY" },
    { ticker: "BRKM5", nome: "Braskem", tipo: "EQUITY" },
    { ticker: "BRAP4", nome: "Bradespar", tipo: "EQUITY" },
    { ticker: "JHSF3", nome: "JHSF", tipo: "EQUITY" },
    { ticker: "ALOS3", nome: "Allos", tipo: "EQUITY" },
    { ticker: "OIBR3", nome: "Oi", tipo: "EQUITY" },
    { ticker: "PSSA3", nome: "Porto Seguro", tipo: "EQUITY" },
    { ticker: "LJQQ3", nome: "Lojas Quero-Quero", tipo: "EQUITY" },
    { ticker: "AZZA3", nome: "Arezzo", tipo: "EQUITY" },
    { ticker: "ELET6", nome: "Eletrobras", tipo: "EQUITY" },
    { ticker: "KLBN4", nome: "Klabin", tipo: "EQUITY" },
    { ticker: "AZEV4", nome: "Azevedo & Travassos", tipo: "EQUITY" },
    { ticker: "GGPS3", nome: "GPS", tipo: "EQUITY" },
    { ticker: "SANB11", nome: "Banco Santander", tipo: "EQUITY" },
    { ticker: "TAEE11", nome: "Taesa", tipo: "EQUITY" },